add retries and delays to work around ESP32-S3 problems
adafruit/Adafruit_CircuitPython_LC709203F pull request #21
Opened 2022-11-10 01:49 UTC by dhalbert

ESP32-S3 has some issues with the clock-stretching and sleeping done by the LC709203F. See https://github.com/adafruit/circuitpython/issues/6311.

- Add retries when scanning for the device, and also add some delays during setup. This seems to mostly ameliorate the problems on the S3.
- Raise `ValueError` for bad args, not `AttributeError`.
- Raise `OSError` instead of `RuntimeError` on CRC failure. This makes it easier to catch all read/write failures so you can retry.

Tested with this program. Note the `try`-`except` which catches `OSError`. There can still be occasional failures, so it's good to catch and retry.

```py
import time
import board
import busio
from adafruit_lc709203f import LC709203F, PackSize

uart = board.UART()
battery_monitor = LC709203F(board.I2C())
battery_monitor.pack_size = PackSize.MAH400

while True:
    try:
        print("Battery Percent: {:.2f} %".format(battery_monitor.cell_percent))
        print("Battery Voltage: {:.2f} V".format(battery_monitor.cell_voltage))

        uart.write(b"Battery Percent: {:.2f} %\r\n".format(battery_monitor.cell_percent))
        uart.write(b"Battery Voltage: {:.2f} V\r\n".format(battery_monitor.cell_voltage))
    except OSError:
        print("retrying reads")

    time.sleep(2)
```

@Gingertrout @BeatArnet @mopore @ThomasAtBBTF Could you try this changed version and see if it works for you? Thank you. You just need to copy the `adafruit_lc709203f.py` file in this pull request to your CIRCUITPY drive, which will override what is in your `lib/`.

2022-11-10 09:44 UTC, BeatArnet commented
After downloading the latest version of the adafruit_lc709203f.mpy library and running your sample code on my feather_s3_tft I got the following errors:

>>> %Run -c $EDITOR_CONTENT
Zurückverfolgung (jüngste Aufforderung zuletzt):
  Datei "<stdin>", Zeile 7, in <module>
  Datei "adafruit_lc709203f.py", Zeile 132, in __init__
  Datei "adafruit_lc709203f.py", Zeile 136, in init_RSOC
  Datei "adafruit_lc709203f.py", Zeile 257, in _write_word
OSError: [Errno 116] ETIMEDOUT
>>>

2022-11-10 12:38 UTC, dhalbert commented
@BeatArnet The proposed fix is not yet available as .mpy. Please try:
https://github.com/adafruit/Adafruit_CircuitPython_LC709203F/blob/1007e4c96bc465204de0cb5a3684022e9e0fb71b/adafruit_lc709203f.py

2022-11-10 14:36 UTC, BeatArnet commented
Unfortunately, after some impressive results…:

 

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

Battery Percent: 100.00 %

Battery Voltage: 4.19 V

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

retrying reads

 

 

 

Von: Dan Halbert ***@***.***> 
Gesendet: Donnerstag, 10. November 2022 13:39
An: adafruit/Adafruit_CircuitPython_LC709203F ***@***.***>
Cc: Beat Arnet ***@***.***>; Mention ***@***.***>
Betreff: Re: [adafruit/Adafruit_CircuitPython_LC709203F] add retries and delays to work around ESP32-S3 problems (PR #21)

 

@BeatArnet <https://github.com/BeatArnet>  The proposed fix is not yet available as .mpy. Please try:
https://github.com/adafruit/Adafruit_CircuitPython_LC709203F/blob/1007e4c96bc465204de0cb5a3684022e9e0fb71b/adafruit_lc709203f.py

—
Reply to this email directly, view it on GitHub <https://github.com/adafruit/Adafruit_CircuitPython_LC709203F/pull/21#issuecomment-1310221518> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA2L6HP76MVF2NNVR2ONOYLWHTUGJANCNFSM6AAAAAAR4BU2SI> .
You are receiving this because you were mentioned.  <https://github.com/notifications/beacon/AA2L6HO3XIN32OMTHKXMESLWHTUGJA5CNFSM6AAAAAAR4BU2SKWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSODBSM4.gif> Message ID: ***@***.*** ***@***.***> >

2022-11-10 14:45 UTC, dhalbert commented
@BeatArnet hmm, I saw a few missing reads, but not continuous as you did :slightly_frowning_face: . Are you using exactly the same test program, and which board are you testing on?

2022-11-10 15:21 UTC, BeatArnet commented
I used your sample-code and the latest library *.py. I have an Adafruit S3 TFT board.

Von: Dan Halbert ***@***.***> 
Gesendet: Donnerstag, 10. November 2022 15:45
An: adafruit/Adafruit_CircuitPython_LC709203F ***@***.***>
Cc: Beat Arnet ***@***.***>; Mention ***@***.***>
Betreff: Re: [adafruit/Adafruit_CircuitPython_LC709203F] add retries and delays to work around ESP32-S3 problems (PR #21)

 

@BeatArnet <https://github.com/BeatArnet>  hmm, I saw a few missing reads, but not continuous as you did 🙁 . Are you using exactly the same test program, and which board are you testing on?

—
Reply to this email directly, view it on GitHub <https://github.com/adafruit/Adafruit_CircuitPython_LC709203F/pull/21#issuecomment-1310400053> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA2L6HOC44TWVEXSII63TIDWHUC7ZANCNFSM6AAAAAAR4BU2SI> .
You are receiving this because you were mentioned.  <https://github.com/notifications/beacon/AA2L6HNCIQWBWEYMBV2KNADWHUC7ZA5CNFSM6AAAAAAR4BU2SKWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSODMPDK.gif> Message ID: ***@***.*** ***@***.***> >

2022-11-11 04:01 UTC, tekktrik approved these changes
All makes sense to me!  Question of of curiosity, why is `ValueError` what's being raised by the failed instancing of `I2CDevice` and not something like `OSError` itself?

2022-11-11 04:03 UTC, tekktrik requested changes
Ah, I missed the ongoing conversation.  Requesting changes so it doesn't show as "approved" until that's sorted out, my bad!

2022-12-19 16:43 UTC, FoamyGuy approved these changes
These changes look good to me. I think it's worthwhile to go ahead and merge this improvement even if there is still some situations that can still be problematic for other reasons. 

I tested the code posted in this PR on a Feather S3 TFT with 8.0.0.beta.5. It has run successfully for several minutes for me with the branch from this PR.

@dhalbert or @tekktrik Do we have any specific reason to hold off merging this? It seems like there may still be underlying issues from upstream that can cause trouble, but the improvements here seem to stand on their own as well for this library.

2022-12-19 17:02 UTC, tekktrik commented
I'll defer to @dhalbert but I agree with you.

Also, I didn't fully realize until now that CircuitPython implemented the `for`/`else` combination, cool!  I think this is the first time I've actually seen it in action.

2022-12-19 17:22 UTC, dhalbert commented
@FoamyGuy @tekktrik I did not merge it because @BeatArnet still had trouble. But it may be particular samples. So ok, let's merge it, and it will fix the problem at least some of the time.

2022-12-19 17:39 UTC, merged

2022-12-19 18:47 UTC, BeatArnet commented
I could solve the problems, using the following code:

```py
# The following code for scanning the I2C addresses is necessary so that the voltage can be measured
BATTERY_MON_ADDRESS = 0x0B  # Address for ESP32-s3 tft Feather

def hack_for_i2c_issue():
    i2c = board.I2C()
    while not i2c.try_lock():
        pass
    running = True
    try:
        while running:
            print("I2C addresses found:", 
                [hex(device_address) for device_address in i2c.scan()]
            )
            # time.sleep(2)
            running = False
        return i2c
    finally:  # unlock the i2c bus when ctrl-c'ing out of the loop
        i2c.unlock()

try:
    print("Searching for battery monitor...")

    i2c = hack_for_i2c_issue()
    battery_monitor = LC709203F(i2c)
```

For me, the problem is solved with the above hack.

2022-12-20 00:03 UTC, dhalbert commented
@BeatArnet The code I added is similar to your hack, but only tries three times to wake up the LC709203F. However, if it doesn't succeed, it will throw an exception. So I don't know why your eventually gets read failures. Perhaps the sensor is going back to sleep in a scenario I hadn't envisioned. We could retry reads a few times as well.