Allow configuration of the low voltage alarm
adafruit/Adafruit_CircuitPython_LC709203F pull request #25
Opened 2023-04-24 21:45 UTC by jrrickerson

Enable read/write properties for the 0x13 (low voltage RSOC threshold) and 0x14 (low voltage value register)
Fixes #12

NOTE: Untested so far on hardware due to lack of availability.

2023-04-24 22:20 UTC, tekktrik requested changes
Looks like this is failing the CI.  You can use `pre-commit` to help fix the issues it's having.  You can find information on how to install and use `pre-commit` here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

2023-04-26 23:01 UTC, jrrickerson commented
@tekktrik Not trying to be pushy or impatient, but was there anything else I should do with this to mark it as ready for a merge?  Just trying to make sure you weren't waiting on me for something!  I realize there's a ton of stuff to review though so if that's all it is that's fine too! :smile:

2023-04-27 14:41 UTC, tekktrik commented
Hey!  Sorry for the delay, I'll take a look today and let you know, but as of right now you're all set!

2023-04-28 12:10 UTC, tekktrik requested changes
Looks good to me!  One quick thing:

2023-04-28 12:10 UTC, tekktrik commented on adafruit_lc709203f.py
> +        if not 0 < percent < 100:
Should this be `0 <= percent <= 100`?

2023-04-28 16:38 UTC, jrrickerson commented on adafruit_lc709203f.py
> +        if not 0 < percent < 100:
Ack, you're totally right.  Sorry for the oversight - fixed in my latest push.

2023-05-01 13:46 UTC, tekktrik approved these changes
Looks good to me!  Thanks for the addition!

2023-05-01 13:47 UTC, tekktrik commented
Didn't test but verified against datasheet.

2023-05-01 13:47 UTC, merged